/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.universidad.vista;

import com.mycompany.universidad.modelo.Carrera;
import com.mycompany.universidad.Universidad;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author jose
 */
public class PantallaAlumno extends javax.swing.JFrame {

    /**
     * Creates new form PantallaAlumno
     */
    public PantallaAlumno( ArrayList<Carrera> carreras) {
        initComponents();
        setSize(700,600 );
        setLocation(600, 200);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        setVisible(true);
        setResizable(false);
        
        cargarCarrerasEnListado(carreras);
        
    }

    private void cargarCarrerasEnListado(ArrayList<Carrera> carreras){
        
        DefaultListModel modelo = new DefaultListModel();
        
        if (!carreras.isEmpty()){
            


            //tengo que publicar en la lista las carreras disponibls
            for (int i = 0; i < carreras.size() ; i++) {

                modelo.addElement(carreras.get(i).toString());    

            }
        }else{
            
            modelo.addElement(" No hay carreras agregadas");
        }
        
        jListCarrerasDisponibles.setModel(modelo);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAlumno = new javax.swing.JLabel();
        jLabelNombreAlumno = new javax.swing.JLabel();
        jLabelDocumentoAlumno = new javax.swing.JLabel();
        jTextFieldDocAlumno = new javax.swing.JTextField();
        jTextFieldNombreAlumno1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCarrerasDisponibles = new javax.swing.JList<>();
        jLabelSeleccionarCarrera = new javax.swing.JLabel();
        jButtonInscribirAlumno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAlumno.setText("Inscripcion Alumno");

        jLabelNombreAlumno.setText("Nombre Alumno");

        jLabelDocumentoAlumno.setText("Documento ");

        jListCarrerasDisponibles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListCarrerasDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListCarrerasDisponiblesMouseClicked(evt);
            }
        });
        jListCarrerasDisponibles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCarrerasDisponiblesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListCarrerasDisponibles);

        jLabelSeleccionarCarrera.setText("Seleccionar Carrera");

        jButtonInscribirAlumno.setText("INSCRIBIR");
        jButtonInscribirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscribirAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDocumentoAlumno)
                        .addGap(94, 94, 94))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNombreAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addGap(71, 71, 71)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombreAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDocAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSeleccionarCarrera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(408, 408, 408))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jButtonInscribirAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabelAlumno)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelAlumno)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombreAlumno)
                    .addComponent(jTextFieldNombreAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDocumentoAlumno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDocAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jLabelSeleccionarCarrera)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButtonInscribirAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListCarrerasDisponiblesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCarrerasDisponiblesValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jListCarrerasDisponiblesValueChanged

    private void jListCarrerasDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListCarrerasDisponiblesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListCarrerasDisponiblesMouseClicked

    private void jButtonInscribirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscribirAlumnoActionPerformed
                // TODO add your handling code here:
                
                
       //inscribo el alumno en una carrera 
       int carreraSeleccionada = jListCarrerasDisponibles.getSelectedIndex();
       
       // mando el indice de la carrera seleccionada, -1 xq arranca en 0
       Universidad.inscribirAlumno(carreraSeleccionada, this.jTextFieldNombreAlumno1.getText(), Integer.valueOf(this.jTextFieldDocAlumno.getText() )); 
        
       
       dispose();
                
                
    }//GEN-LAST:event_jButtonInscribirAlumnoActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PantallaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PantallaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PantallaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PantallaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PantallaAlumno(null).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInscribirAlumno;
    private javax.swing.JLabel jLabelAlumno;
    private javax.swing.JLabel jLabelDocumentoAlumno;
    private javax.swing.JLabel jLabelNombreAlumno;
    private javax.swing.JLabel jLabelSeleccionarCarrera;
    private javax.swing.JList<String> jListCarrerasDisponibles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldDocAlumno;
    private javax.swing.JTextField jTextFieldNombreAlumno1;
    // End of variables declaration//GEN-END:variables
}
