/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.universidad.vista;

import com.mycompany.universidad.modelo.Alumno;
import com.mycompany.universidad.modelo.HistoricoMateria;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class PantallaCargaNotas extends javax.swing.JFrame {

    private HistoricoMateria historico;
    private Alumno alumno;
    
    /**
     * Creates new form PantallaCargaNotas
     * @param historicoMateria
     */
    public PantallaCargaNotas( HistoricoMateria historicoMateria, Alumno alumno) {
        initComponents();
        
        setSize(400,450 );
        setLocation(600, 200);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        setVisible(true);
        
        this.historico = historicoMateria;
        this.alumno = alumno;
        
        
        if (! this.historico.getMateria().isPromocionable() ){
            
           // this.jTextFieldTeorico.setVisible(false);
            
            this.jTextFieldTeorico.setEnabled(false);
        }
        
        
        cargarHistorico();
    }  
        
    private void cargarHistorico (){
        //cargo los valores del formulario
        
        
        this.jLabelNombreMateria.setText(this.historico.getMateria().getNombre());
        
        
        if ( historico.getParcial1() != null ){

            this.jTextField1Parcial.setText( (String ) (this.historico.getParcial1().toString()));
            
        }
        
//        if ( historico.getParcial2() != null ){
//
//            this.jTextField2Parcial.setText( (String ) (this.historico.getParcial2().toString()));
//            
//        }
//        
        if (historico.getRec1() != null){
            
            this.jTextField1rec.setText( (String ) (this.historico.getRec1().toString()));
        }
//        
//        if (historico.getRec2() != null){
//            
//            this.jTextField2rec.setText( (String ) (this.historico.getRec2().toString()));
//        }
        
        if (historico.getTeorico() != null){
            
            this.jTextFieldTeorico.setText( (String ) (this.historico.getTeorico().toString()));
        }
        
        if (historico.getNotaFinal() != null){
            
            this.jTextFieldNotaFinal.setText( (String ) (this.historico.getNotaFinal().toString()));
        
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1Parcial = new javax.swing.JTextField();
        jTextField1rec = new javax.swing.JTextField();
        jTextFieldTeorico = new javax.swing.JTextField();
        jTextFieldNotaFinal = new javax.swing.JTextField();
        jLabelNombreMateria = new javax.swing.JLabel();
        jButtonTerminarCargarNotas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Parcial");

        jLabel3.setText("Recuperatorio");

        jLabel5.setText("Teorico");

        jLabel6.setText("Nota final");

        jTextField1rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1recActionPerformed(evt);
            }
        });

        jLabelNombreMateria.setText("jLabel7");

        jButtonTerminarCargarNotas.setText("Terminar");
        jButtonTerminarCargarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminarCargarNotasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelNombreMateria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNotaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jTextFieldTeorico)
                    .addComponent(jTextField1Parcial)
                    .addComponent(jTextField1rec, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTerminarCargarNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelNombreMateria)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1Parcial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTeorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNotaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jButtonTerminarCargarNotas)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTerminarCargarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminarCargarNotasActionPerformed
        
        //seteo los valores ingresados en el historico
        try{
            
            if ( ! this.jTextField1Parcial.getText().equals("")){
                
                this.historico.setParcial1(Integer.valueOf(this.jTextField1Parcial.getText()));
            }
            
//            if ( ! this.jTextField2Parcial.getText().equals("")){
//                
//                this.historico.setParcial2(Integer.valueOf(this.jTextField2Parcial.getText()));
//            }
//
            if  ( ! this.jTextField1rec.getText().equals("")){
    
                this.historico.setRec1(Integer.valueOf(this.jTextField1rec.getText()));
            }
//               
//            if  ( ! this.jTextField2rec.getText().equals("")){
//                
//                this.historico.setRec2(Integer.valueOf(this.jTextField2rec.getText()));
//            }
            //pregunto si la materia es promosionable
            if (this.jTextFieldTeorico.isVisible() ){
                
               if  ( ! this.jTextFieldTeorico.getText().equals("")){
                
                    this.historico.setTeorico(Integer.valueOf(this.jTextFieldTeorico.getText()));
                }
    
            }
            

            if  ( ! this.jTextFieldNotaFinal.getText().equals("") &&  this.jTextField1Parcial.getText().equals("")){
                
                JOptionPane.showMessageDialog(rootPane, "Es necesario una nota de parcial", "Aviso", 2);
                 
            }else{
                
                if (! this.jTextFieldNotaFinal.getText().equals("") ){
                    
                    this.historico.setNotaFinal(Integer.valueOf(this.jTextFieldNotaFinal.getText()));
                    
                }
                
            }
            //actualizo el historico
            System.out.println("Actualizo el historico");
            this.alumno.actualizarHistorico(this.historico, this.historico.getMateria().getSemestre(), this.historico.getMateria().getNombre());
            
            
        }catch(Exception  e){
            e.printStackTrace();
            System.out.println("no se introdujeron todos los valores");
        }
        
        
        limpiarCampos();
        dispose();
        
    }//GEN-LAST:event_jButtonTerminarCargarNotasActionPerformed

    private void jTextField1recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1recActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1recActionPerformed

    
    private void limpiarCampos(){
        
        this.jLabelNombreMateria.setText("");
        
        //limpio los valores del formulario

            this.jTextField1Parcial.setText("");
            
//            this.jTextField2Parcial.setText("");
//            
            this.jTextField1rec.setText("");
//       
//            this.jTextField2rec.setText("");
            
            this.jTextFieldTeorico.setText("");
            
            this.jTextFieldNotaFinal.setText("");
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PantallaCargaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PantallaCargaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PantallaCargaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PantallaCargaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PantallaCargaNotas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTerminarCargarNotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelNombreMateria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1Parcial;
    private javax.swing.JTextField jTextField1rec;
    private javax.swing.JTextField jTextFieldNotaFinal;
    private javax.swing.JTextField jTextFieldTeorico;
    // End of variables declaration//GEN-END:variables
}
