/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.universidad.vista;

import com.mycompany.universidad.modelo.Materia;
import com.mycompany.universidad.modelo.PlanEstudio;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class PantallaPlanCarrera extends javax.swing.JFrame {
    
    PlanEstudio plan;
    /**
     * Creates new form PantallaPlanCarrera
     */
    public PantallaPlanCarrera(PlanEstudio plan, String nombreCarrera, Integer optativas) {
        initComponents();
        
        setSize(900,500 );
        setLocation(600, 200);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        
        this.plan = plan;
        this.jLabelNombreCarrera.setText(nombreCarrera);
        this.jLabelTipoPlan.setText( "Tipo de plan: " + (String.valueOf (plan.getTipoPlan() ))  );
        this.jLabelcantOptativas.setText("Cant materias optativas obligatoras: "+ optativas );
        
        cargarMaterias(plan);
        
        setVisible(true);
        
    }

    
    private void cargarMaterias(PlanEstudio plan){
        
        ArrayList<ArrayList <Materia> > materias = plan.getCuatrimestres();
        
        
        System.out.println("Entramos en el metodo para completar la tabla...");
        
        System.out.println("tamaño de lista materias " +  materias.size() );
        
        
        //recibo una lista de materias para mostrar
        for (int i = 1; i < materias.size(); i++) {
            
            for (int j = 0; j < materias.get(i).size(); j++) {
                
                System.out.println("tamaño de lista materias del cuat " +  i + ": " + materias.get(i ).size());
                
                
                String nombreMateria = materias.get(i).get(j).getNombre();
                    
                //seteo el nombre de la materia en la tabla
                jTableMaterias.getModel().setValueAt(nombreMateria, j, i - 1);
                
            }
        }
    }
        
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombreCarrera = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterias = new javax.swing.JTable();
        jLabelTipoPlan = new javax.swing.JLabel();
        jLabelcantOptativas = new javax.swing.JLabel();
        jButtonVerMateria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNombreCarrera.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelNombreCarrera.setText("jLabel1");

        jTableMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cuat 1", "Cuat 2", "Cuat 3", "Cuat 4", "Cuat 5", "Cuat 6", "Cuat 7", "Cuat 8", "Cuat 9", "Cuat 10"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMaterias.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTableMaterias);

        jLabelTipoPlan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelTipoPlan.setText("jLabel1");

        jLabelcantOptativas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelcantOptativas.setText("jLabel1");

        jButtonVerMateria.setText("Ver Materia");
        jButtonVerMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(311, 311, 311)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelTipoPlan)
                                        .addGap(118, 118, 118)
                                        .addComponent(jLabelcantOptativas))
                                    .addComponent(jLabelNombreCarrera)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(318, 318, 318)
                                .addComponent(jButtonVerMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNombreCarrera)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoPlan)
                    .addComponent(jLabelcantOptativas))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVerMateria)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerMateriaActionPerformed
        // TODO add your handling code here:
        
        if (this.jTableMaterias.getSelectedRowCount()> 0  && this.jTableMaterias.getSelectedColumnCount()> 0 ){
            
            int fila = this.jTableMaterias.getSelectedRow();
            int column = this.jTableMaterias.getSelectedColumn();
            
            if (this.jTableMaterias.getValueAt(fila, column) != null ){
                
                String materia = (String) this.jTableMaterias.getValueAt(fila, column);
                Materia m = this.plan.obtenerMateriaPorNombre(materia);
               
                PantallaDetalleMateria pantallaDetalle = new PantallaDetalleMateria(m.getNombre(), m.getSemestre(), m.getCorrelativaAnterior() != null ? m.getCorrelativaAnterior().getNombre() : "no tiene", m.getProfesor() != null ? m.getProfesor() : "no tiene");
    
            }else{
            
                JOptionPane.showMessageDialog(rootPane, "Seleccione alguna materia valida", "Aviso", 2);
            }
        }else{
            
            JOptionPane.showMessageDialog(rootPane, "Seleccione alguna materia", "Aviso", 2);
        }
    }//GEN-LAST:event_jButtonVerMateriaActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PantallaPlanCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PantallaPlanCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PantallaPlanCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PantallaPlanCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PantallaPlanCarrera().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVerMateria;
    private javax.swing.JLabel jLabelNombreCarrera;
    private javax.swing.JLabel jLabelTipoPlan;
    private javax.swing.JLabel jLabelcantOptativas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMaterias;
    // End of variables declaration//GEN-END:variables
}
